import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse(`{"title":"Katton Introduction","description":"","frontmatter":{},"headers":[{"level":2,"title":"What is Katton?","slug":"what-is-katton","link":"#what-is-katton","children":[]},{"level":2,"title":"Why Katton?","slug":"why-katton","link":"#why-katton","children":[]},{"level":2,"title":"I don't know Kotlin","slug":"i-don-t-know-kotlin","link":"#i-don-t-know-kotlin","children":[]}],"relativePath":"quickstart/index.md","filePath":"quickstart/index.md"}`);
const _sfc_main = { name: "quickstart/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="katton-introduction" tabindex="-1">Katton Introduction <a class="header-anchor" href="#katton-introduction" aria-label="Permalink to &quot;Katton Introduction&quot;">​</a></h1><p>Welcome to Katton. This wiki contains documentation and guides for using the Katton modding framework. Whether you&#39;re a beginner looking to get started or an experienced modder seeking advanced tips, you&#39;ll find valuable information here.</p><h2 id="what-is-katton" tabindex="-1">What is Katton? <a class="header-anchor" href="#what-is-katton" aria-label="Permalink to &quot;What is Katton?&quot;">​</a></h2><p>Katton is a powerful modding framework for Minecraft that allows you to use Kotlin scripts to create and modify game content. With hot-reloadable scripts, you can see your changes in real-time without needing to restart the game.</p><h2 id="why-katton" tabindex="-1">Why Katton? <a class="header-anchor" href="#why-katton" aria-label="Permalink to &quot;Why Katton?&quot;">​</a></h2><ul><li><strong>Ease of Use</strong>: Katton&#39;s intuitive API and hot-reload feature make it easy for modders of all skill levels to create and test their mods quickly.</li><li><strong>Flexibility</strong>: With Kotlin&#39;s powerful features, you can create complex mods that interact with Minecraft in unique ways.</li><li><strong>Performance</strong>: Katton uses Kotlin Scripts to directly interact with Java objects during the runtime of Minecraft, ensuring high performance and seamless integration.</li><li><strong>Powerful API</strong>: Katton provides a comprehensive API that allows you to access and modify various aspects of the game, from blocks and items to entities and world generation, even code injections like mixins, and <strong>ALL HOT-RELOADABLE</strong>.</li></ul><h2 id="i-don-t-know-kotlin" tabindex="-1">I don&#39;t know Kotlin <a class="header-anchor" href="#i-don-t-know-kotlin" aria-label="Permalink to &quot;I don&#39;t know Kotlin&quot;">​</a></h2><p>Don&#39;t worry! Kotlin is a modern programming language that is easy to learn, especially if you have experience with Java or other C-style languages. There are plenty of resources available online to help you get started with Kotlin, including the official <a href="https://kotlinlang.org/docs/home.html" target="_blank" rel="noreferrer">Kotlin documentation</a> and various tutorials on platforms like YouTube and Udemy.</p><hr><p>In the following sections, you&#39;ll find guides on how to get started with Katton, as well as detailed documentation of the API and examples to help you create your own mods.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("quickstart/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
